spring:
  application:
    name: EK_Provider
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5   #设置每隔5秒进行与服务器进行心跳测试
    leaseExpirationDurationInSeconds: 10 #当心跳测试没有心跳测试、或者任何请求的时间超过10秒（默认90秒），就将这个服务从服务列表剔除
    metadata-map:  #这个用来设置属性值，服务的调用者可以获取这个值
        company-name: crazyit
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      