// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deptsprotos.proto

package com.example.protobuf.depts;

public final class DeptsProtos {
  private DeptsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeparmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .depts.Deparment.Person person = 3;
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    java.util.List<DeptsProtos.Deparment.Person>
        getPersonList();
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    DeptsProtos.Deparment.Person getPerson(int index);
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    java.util.List<? extends DeptsProtos.Deparment.PersonOrBuilder>
        getPersonOrBuilderList();
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    DeptsProtos.Deparment.PersonOrBuilder getPersonOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code depts.Deparment}
   */
  public static final class Deparment extends
      com.google.protobuf.GeneratedMessage
      implements DeparmentOrBuilder {
    // Use Deparment.newBuilder() to construct.
    private Deparment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Deparment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Deparment defaultInstance;
    public static Deparment getDefaultInstance() {
      return defaultInstance;
    }

    public Deparment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Deparment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                person_ = new java.util.ArrayList<DeptsProtos.Deparment.Person>();
                mutable_bitField0_ |= 0x00000004;
              }
              person_.add(input.readMessage(DeptsProtos.Deparment.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeptsProtos.internal_static_depts_Deparment_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeptsProtos.internal_static_depts_Deparment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeptsProtos.Deparment.class, DeptsProtos.Deparment.Builder.class);
    }

    public static com.google.protobuf.Parser<Deparment> PARSER =
        new com.google.protobuf.AbstractParser<Deparment>() {
      public Deparment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Deparment(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Deparment> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code depts.Deparment.PersonType}
     */
    public enum PersonType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEADER = 1;</code>
       */
      LEADER(0, 1),
      /**
       * <code>ORDINARY = 2;</code>
       */
      ORDINARY(1, 2),
      ;

      /**
       * <code>LEADER = 1;</code>
       */
      public static final int LEADER_VALUE = 1;
      /**
       * <code>ORDINARY = 2;</code>
       */
      public static final int ORDINARY_VALUE = 2;


      public final int getNumber() { return value; }

      public static PersonType valueOf(int value) {
        switch (value) {
          case 1: return LEADER;
          case 2: return ORDINARY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PersonType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PersonType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PersonType>() {
              public PersonType findValueByNumber(int number) {
                return PersonType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DeptsProtos.Deparment.getDescriptor().getEnumTypes().get(0);
      }

      private static final PersonType[] VALUES = values();

      public static PersonType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PersonType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:depts.Deparment.PersonType)
    }

    public interface PersonOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required int32 id = 2;
      /**
       * <code>required int32 id = 2;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 2;</code>
       */
      int getId();

      // optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];
      /**
       * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
       */
      boolean hasType();
      /**
       * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
       */
      DeptsProtos.Deparment.PersonType getType();
    }
    /**
     * Protobuf type {@code depts.Deparment.Person}
     */
    public static final class Person extends
        com.google.protobuf.GeneratedMessage
        implements PersonOrBuilder {
      // Use Person.newBuilder() to construct.
      private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Person defaultInstance;
      public static Person getDefaultInstance() {
        return defaultInstance;
      }

      public Person getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Person(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                id_ = input.readInt32();
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                DeptsProtos.Deparment.PersonType value = DeptsProtos.Deparment.PersonType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  bitField0_ |= 0x00000004;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeptsProtos.internal_static_depts_Deparment_Person_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeptsProtos.internal_static_depts_Deparment_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeptsProtos.Deparment.Person.class, DeptsProtos.Deparment.Person.Builder.class);
      }

      public static com.google.protobuf.Parser<Person> PARSER =
          new com.google.protobuf.AbstractParser<Person>() {
        public Person parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Person> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required int32 id = 2;
      public static final int ID_FIELD_NUMBER = 2;
      private int id_;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }

      // optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];
      public static final int TYPE_FIELD_NUMBER = 3;
      private DeptsProtos.Deparment.PersonType type_;
      /**
       * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
       */
      public DeptsProtos.Deparment.PersonType getType() {
        return type_;
      }

      private void initFields() {
        name_ = "";
        id_ = 0;
        type_ = DeptsProtos.Deparment.PersonType.ORDINARY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, id_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeEnum(3, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, id_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static DeptsProtos.Deparment.Person parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DeptsProtos.Deparment.Person parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DeptsProtos.Deparment.Person parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DeptsProtos.Deparment.Person parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DeptsProtos.Deparment.Person parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static DeptsProtos.Deparment.Person parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static DeptsProtos.Deparment.Person parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static DeptsProtos.Deparment.Person parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static DeptsProtos.Deparment.Person parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static DeptsProtos.Deparment.Person parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(DeptsProtos.Deparment.Person prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code depts.Deparment.Person}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements DeptsProtos.Deparment.PersonOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return DeptsProtos.internal_static_depts_Deparment_Person_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return DeptsProtos.internal_static_depts_Deparment_Person_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DeptsProtos.Deparment.Person.class, DeptsProtos.Deparment.Person.Builder.class);
        }

        // Construct using com.example.depts.DeptsProtos.Deparment.Person.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = DeptsProtos.Deparment.PersonType.ORDINARY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return DeptsProtos.internal_static_depts_Deparment_Person_descriptor;
        }

        public DeptsProtos.Deparment.Person getDefaultInstanceForType() {
          return DeptsProtos.Deparment.Person.getDefaultInstance();
        }

        public DeptsProtos.Deparment.Person build() {
          DeptsProtos.Deparment.Person result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public DeptsProtos.Deparment.Person buildPartial() {
          DeptsProtos.Deparment.Person result = new DeptsProtos.Deparment.Person(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DeptsProtos.Deparment.Person) {
            return mergeFrom((DeptsProtos.Deparment.Person)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DeptsProtos.Deparment.Person other) {
          if (other == DeptsProtos.Deparment.Person.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {

            return false;
          }
          if (!hasId()) {

            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DeptsProtos.Deparment.Person parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DeptsProtos.Deparment.Person) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required int32 id = 2;
        private int id_ ;
        /**
         * <code>required int32 id = 2;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 id = 2;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 2;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000002;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 2;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          id_ = 0;
          onChanged();
          return this;
        }

        // optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];
        private DeptsProtos.Deparment.PersonType type_ = DeptsProtos.Deparment.PersonType.ORDINARY;
        /**
         * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
         */
        public DeptsProtos.Deparment.PersonType getType() {
          return type_;
        }
        /**
         * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
         */
        public Builder setType(DeptsProtos.Deparment.PersonType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .depts.Deparment.PersonType type = 3 [default = ORDINARY];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = DeptsProtos.Deparment.PersonType.ORDINARY;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:depts.Deparment.Person)
      }

      static {
        defaultInstance = new Person(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:depts.Deparment.Person)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .depts.Deparment.Person person = 3;
    public static final int PERSON_FIELD_NUMBER = 3;
    private java.util.List<DeptsProtos.Deparment.Person> person_;
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    public java.util.List<DeptsProtos.Deparment.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    public java.util.List<? extends DeptsProtos.Deparment.PersonOrBuilder>
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    public DeptsProtos.Deparment.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .depts.Deparment.Person person = 3;</code>
     */
    public DeptsProtos.Deparment.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(3, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeptsProtos.Deparment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeptsProtos.Deparment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeptsProtos.Deparment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeptsProtos.Deparment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeptsProtos.Deparment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeptsProtos.Deparment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeptsProtos.Deparment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeptsProtos.Deparment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeptsProtos.Deparment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeptsProtos.Deparment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeptsProtos.Deparment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code depts.Deparment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DeptsProtos.DeparmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeptsProtos.internal_static_depts_Deparment_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeptsProtos.internal_static_depts_Deparment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeptsProtos.Deparment.class, DeptsProtos.Deparment.Builder.class);
      }

      // Construct using com.example.depts.DeptsProtos.Deparment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeptsProtos.internal_static_depts_Deparment_descriptor;
      }

      public DeptsProtos.Deparment getDefaultInstanceForType() {
        return DeptsProtos.Deparment.getDefaultInstance();
      }

      public DeptsProtos.Deparment build() {
        DeptsProtos.Deparment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeptsProtos.Deparment buildPartial() {
        DeptsProtos.Deparment result = new DeptsProtos.Deparment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeptsProtos.Deparment) {
          return mergeFrom((DeptsProtos.Deparment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeptsProtos.Deparment other) {
        if (other == DeptsProtos.Deparment.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000004);
              personBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasName()) {

          return false;
        }
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeptsProtos.Deparment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeptsProtos.Deparment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .depts.Deparment.Person person = 3;
      private java.util.List<DeptsProtos.Deparment.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          person_ = new java.util.ArrayList<DeptsProtos.Deparment.Person>(person_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          DeptsProtos.Deparment.Person, DeptsProtos.Deparment.Person.Builder, DeptsProtos.Deparment.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public java.util.List<DeptsProtos.Deparment.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public DeptsProtos.Deparment.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder setPerson(
          int index, DeptsProtos.Deparment.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder setPerson(
          int index, DeptsProtos.Deparment.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder addPerson(DeptsProtos.Deparment.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder addPerson(
          int index, DeptsProtos.Deparment.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder addPerson(
          DeptsProtos.Deparment.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder addPerson(
          int index, DeptsProtos.Deparment.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder addAllPerson(
          Iterable<? extends DeptsProtos.Deparment.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public DeptsProtos.Deparment.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public DeptsProtos.Deparment.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public java.util.List<? extends DeptsProtos.Deparment.PersonOrBuilder>
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public DeptsProtos.Deparment.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            DeptsProtos.Deparment.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public DeptsProtos.Deparment.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, DeptsProtos.Deparment.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .depts.Deparment.Person person = 3;</code>
       */
      public java.util.List<DeptsProtos.Deparment.Person.Builder>
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DeptsProtos.Deparment.Person, DeptsProtos.Deparment.Person.Builder, DeptsProtos.Deparment.PersonOrBuilder>
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DeptsProtos.Deparment.Person, DeptsProtos.Deparment.Person.Builder, DeptsProtos.Deparment.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:depts.Deparment)
    }

    static {
      defaultInstance = new Deparment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:depts.Deparment)
  }

  public interface OrganiseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .depts.Deparment depart = 1;
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    java.util.List<DeptsProtos.Deparment>
        getDepartList();
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    DeptsProtos.Deparment getDepart(int index);
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    int getDepartCount();
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    java.util.List<? extends DeptsProtos.DeparmentOrBuilder>
        getDepartOrBuilderList();
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    DeptsProtos.DeparmentOrBuilder getDepartOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code depts.Organise}
   */
  public static final class Organise extends
      com.google.protobuf.GeneratedMessage
      implements OrganiseOrBuilder {
    // Use Organise.newBuilder() to construct.
    private Organise(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Organise(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Organise defaultInstance;
    public static Organise getDefaultInstance() {
      return defaultInstance;
    }

    public Organise getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Organise(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                depart_ = new java.util.ArrayList<DeptsProtos.Deparment>();
                mutable_bitField0_ |= 0x00000001;
              }
              depart_.add(input.readMessage(DeptsProtos.Deparment.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          depart_ = java.util.Collections.unmodifiableList(depart_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeptsProtos.internal_static_depts_Organise_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeptsProtos.internal_static_depts_Organise_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeptsProtos.Organise.class, DeptsProtos.Organise.Builder.class);
    }

    public static com.google.protobuf.Parser<Organise> PARSER =
        new com.google.protobuf.AbstractParser<Organise>() {
      public Organise parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Organise(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Organise> getParserForType() {
      return PARSER;
    }

    // repeated .depts.Deparment depart = 1;
    public static final int DEPART_FIELD_NUMBER = 1;
    private java.util.List<DeptsProtos.Deparment> depart_;
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    public java.util.List<DeptsProtos.Deparment> getDepartList() {
      return depart_;
    }
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    public java.util.List<? extends DeptsProtos.DeparmentOrBuilder>
        getDepartOrBuilderList() {
      return depart_;
    }
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    public int getDepartCount() {
      return depart_.size();
    }
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    public DeptsProtos.Deparment getDepart(int index) {
      return depart_.get(index);
    }
    /**
     * <code>repeated .depts.Deparment depart = 1;</code>
     */
    public DeptsProtos.DeparmentOrBuilder getDepartOrBuilder(
        int index) {
      return depart_.get(index);
    }

    private void initFields() {
      depart_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDepartCount(); i++) {
        if (!getDepart(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < depart_.size(); i++) {
        output.writeMessage(1, depart_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < depart_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, depart_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeptsProtos.Organise parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeptsProtos.Organise parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeptsProtos.Organise parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeptsProtos.Organise parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeptsProtos.Organise parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeptsProtos.Organise parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeptsProtos.Organise parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeptsProtos.Organise parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeptsProtos.Organise parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeptsProtos.Organise parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeptsProtos.Organise prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code depts.Organise}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DeptsProtos.OrganiseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeptsProtos.internal_static_depts_Organise_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeptsProtos.internal_static_depts_Organise_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeptsProtos.Organise.class, DeptsProtos.Organise.Builder.class);
      }

      // Construct using com.example.depts.DeptsProtos.Organise.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDepartFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (departBuilder_ == null) {
          depart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          departBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeptsProtos.internal_static_depts_Organise_descriptor;
      }

      public DeptsProtos.Organise getDefaultInstanceForType() {
        return DeptsProtos.Organise.getDefaultInstance();
      }

      public DeptsProtos.Organise build() {
        DeptsProtos.Organise result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeptsProtos.Organise buildPartial() {
        DeptsProtos.Organise result = new DeptsProtos.Organise(this);
        int from_bitField0_ = bitField0_;
        if (departBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            depart_ = java.util.Collections.unmodifiableList(depart_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.depart_ = depart_;
        } else {
          result.depart_ = departBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeptsProtos.Organise) {
          return mergeFrom((DeptsProtos.Organise)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeptsProtos.Organise other) {
        if (other == DeptsProtos.Organise.getDefaultInstance()) return this;
        if (departBuilder_ == null) {
          if (!other.depart_.isEmpty()) {
            if (depart_.isEmpty()) {
              depart_ = other.depart_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDepartIsMutable();
              depart_.addAll(other.depart_);
            }
            onChanged();
          }
        } else {
          if (!other.depart_.isEmpty()) {
            if (departBuilder_.isEmpty()) {
              departBuilder_.dispose();
              departBuilder_ = null;
              depart_ = other.depart_;
              bitField0_ = (bitField0_ & ~0x00000001);
              departBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDepartFieldBuilder() : null;
            } else {
              departBuilder_.addAllMessages(other.depart_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDepartCount(); i++) {
          if (!getDepart(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeptsProtos.Organise parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeptsProtos.Organise) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .depts.Deparment depart = 1;
      private java.util.List<DeptsProtos.Deparment> depart_ =
        java.util.Collections.emptyList();
      private void ensureDepartIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          depart_ = new java.util.ArrayList<DeptsProtos.Deparment>(depart_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          DeptsProtos.Deparment, DeptsProtos.Deparment.Builder, DeptsProtos.DeparmentOrBuilder> departBuilder_;

      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public java.util.List<DeptsProtos.Deparment> getDepartList() {
        if (departBuilder_ == null) {
          return java.util.Collections.unmodifiableList(depart_);
        } else {
          return departBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public int getDepartCount() {
        if (departBuilder_ == null) {
          return depart_.size();
        } else {
          return departBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public DeptsProtos.Deparment getDepart(int index) {
        if (departBuilder_ == null) {
          return depart_.get(index);
        } else {
          return departBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder setDepart(
          int index, DeptsProtos.Deparment value) {
        if (departBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDepartIsMutable();
          depart_.set(index, value);
          onChanged();
        } else {
          departBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder setDepart(
          int index, DeptsProtos.Deparment.Builder builderForValue) {
        if (departBuilder_ == null) {
          ensureDepartIsMutable();
          depart_.set(index, builderForValue.build());
          onChanged();
        } else {
          departBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder addDepart(DeptsProtos.Deparment value) {
        if (departBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDepartIsMutable();
          depart_.add(value);
          onChanged();
        } else {
          departBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder addDepart(
          int index, DeptsProtos.Deparment value) {
        if (departBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDepartIsMutable();
          depart_.add(index, value);
          onChanged();
        } else {
          departBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder addDepart(
          DeptsProtos.Deparment.Builder builderForValue) {
        if (departBuilder_ == null) {
          ensureDepartIsMutable();
          depart_.add(builderForValue.build());
          onChanged();
        } else {
          departBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder addDepart(
          int index, DeptsProtos.Deparment.Builder builderForValue) {
        if (departBuilder_ == null) {
          ensureDepartIsMutable();
          depart_.add(index, builderForValue.build());
          onChanged();
        } else {
          departBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder addAllDepart(
          Iterable<? extends DeptsProtos.Deparment> values) {
        if (departBuilder_ == null) {
          ensureDepartIsMutable();
          super.addAll(values, depart_);
          onChanged();
        } else {
          departBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder clearDepart() {
        if (departBuilder_ == null) {
          depart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          departBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public Builder removeDepart(int index) {
        if (departBuilder_ == null) {
          ensureDepartIsMutable();
          depart_.remove(index);
          onChanged();
        } else {
          departBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public DeptsProtos.Deparment.Builder getDepartBuilder(
          int index) {
        return getDepartFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public DeptsProtos.DeparmentOrBuilder getDepartOrBuilder(
          int index) {
        if (departBuilder_ == null) {
          return depart_.get(index);  } else {
          return departBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public java.util.List<? extends DeptsProtos.DeparmentOrBuilder>
           getDepartOrBuilderList() {
        if (departBuilder_ != null) {
          return departBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(depart_);
        }
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public DeptsProtos.Deparment.Builder addDepartBuilder() {
        return getDepartFieldBuilder().addBuilder(
            DeptsProtos.Deparment.getDefaultInstance());
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public DeptsProtos.Deparment.Builder addDepartBuilder(
          int index) {
        return getDepartFieldBuilder().addBuilder(
            index, DeptsProtos.Deparment.getDefaultInstance());
      }
      /**
       * <code>repeated .depts.Deparment depart = 1;</code>
       */
      public java.util.List<DeptsProtos.Deparment.Builder>
           getDepartBuilderList() {
        return getDepartFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DeptsProtos.Deparment, DeptsProtos.Deparment.Builder, DeptsProtos.DeparmentOrBuilder>
          getDepartFieldBuilder() {
        if (departBuilder_ == null) {
          departBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DeptsProtos.Deparment, DeptsProtos.Deparment.Builder, DeptsProtos.DeparmentOrBuilder>(
                  depart_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          depart_ = null;
        }
        return departBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:depts.Organise)
    }

    static {
      defaultInstance = new Organise(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:depts.Organise)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_depts_Deparment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_depts_Deparment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_depts_Deparment_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_depts_Deparment_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_depts_Organise_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_depts_Organise_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021deptsprotos.proto\022\005depts\"\317\001\n\tDeparment" +
      "\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\'\n\006person\030\003 \003" +
      "(\0132\027.depts.Deparment.Person\032W\n\006Person\022\014\n" +
      "\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\0223\n\004type\030\003 \001(\0162\033." +
      "depts.Deparment.PersonType:\010ORDINARY\"&\n\n" +
      "PersonType\022\n\n\006LEADER\020\001\022\014\n\010ORDINARY\020\002\",\n\010" +
      "Organise\022 \n\006depart\030\001 \003(\0132\020.depts.Deparme" +
      "ntB \n\021com.example.deptsB\013DeptsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_depts_Deparment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_depts_Deparment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_depts_Deparment_descriptor,
              new String[] { "Id", "Name", "Person", });
          internal_static_depts_Deparment_Person_descriptor =
            internal_static_depts_Deparment_descriptor.getNestedTypes().get(0);
          internal_static_depts_Deparment_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_depts_Deparment_Person_descriptor,
              new String[] { "Name", "Id", "Type", });
          internal_static_depts_Organise_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_depts_Organise_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_depts_Organise_descriptor,
              new String[] { "Depart", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
